---
- name: Install pip
  become: yes
  apt:
    name: python-pip
    state: present

- name: Install pexpect
  become: yes
  pip:
    name: pexpect

- stat: path=/opt/infinit/bin/infinit-user
  register: infinit_exists

- include: install.yml
  when: infinit_exists.stat.exists == False

- name: Setup infinit in systemd
  become: yes
  template:
    src: "templates/infinit-{{ item }}.service.j2"
    dest: "/etc/systemd/system/infinit-{{ item }}.service"
  with_items:
    - network
    - volume

- include: setup_user.yml
  tags: [infinit-configure]

- include: server.yml
  tags: [infinit-configure]
